FROM python:3.13.11-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

# RUN pip install pandas pyarrow
WORKDIR /code

COPY pyproject.toml uv.lock .python-version ./
RUN uv sync --locked

COPY pipeline.py .

ENTRYPOINT [ "uv", "run", "python", "pipeline.py" ]

# docker run -it --rm \
#     -e POSTGRES_USER="root" \
#     -e POSTGRES_PASSWORD="root" \
#     -e POSTGRES_DB="ny_taxi" \
#     -v ny_taxi_postgres_data:/var/lib/postgresql \ 
#     -p 5432:5432 \ 
#     postgres:18